# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"copy_data": "00_utils.ipynb",
         "how_many_in_each_class": "00_utils.ipynb",
         "freeze_unfreeze_layers": "00_utils.ipynb",
         "list_layers": "00_utils.ipynb",
         "evaluate": "00_utils.ipynb",
         "CheckPointManagerCallback": "00_utils.ipynb",
         "download_images": "00_utils.ipynb",
         "verify_images": "00_utils.ipynb",
         "verify_image": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://AmmarAlsharif.github.io/deeplearning_notebooks/"

git_url = "https://github.com/AmmarAlsharif/deeplearning_notebooks/tree/master/"

def custom_doc_links(name): return None
